# Pending github issues
# https://github.com/docker/docker/issues/20708
# https://github.com/docker/compose/pull/2458
# https://github.com/docker/compose/issues/1617

version: '2'

services:

#  ____________________________________________________________________________________________________________
# |____________________________________________________________________________________________________________|

  database:
    image: mdillon/postgis
    container_name: drydock-database
    env_file: .development.env

    ports:
      - "5432:5432"

  queue:
    image: rabbitmq:management
    container_name: drydock-queue
    hostname: drydockqueue
    env_file: .development.env

    ports:
      - "8081:15672"


  cache:
    image: redis:alpine
    container_name: drydock-cache

    ports:
      - "6379"

  #  ____________________________________________________________________________________________________________
  # |____________________________________________________________________________________________________________|

  email:
    image: djfarrelly/maildev
    container_name: drydock-email

    ports:
      - "8082:80"

  #  ____________________________________________________________________________________________________________
  # |____________________________________________________________________________________________________________|

  webapp:

    # As a convenience, I keep the latest copy of the development container built.
    image: atrauzzi/laravel-drydock
    # If however you would like to modify or manage your own development image, comment out the above line
    # and uncomment the next two lines.
    #dockerfile: /Dockerfile
    #build: .

    container_name: drydock-webapp
    env_file: .development.env

    user: ${UID}

    volumes:

      # Bind-mounts for dev.
      - "./laravel:/var/www"
      - "./resources/php-fpm.conf:/etc/php/7.0/fpm/php-fpm.conf"
      - "./resources/php-fpm.www.conf:/etc/php/7.0/fpm/pool.d/www.conf"
      - "./resources/crontab:/etc/cron.d/laravel"
      # Before anyone loses their mind over this... It's only for development!
      - "/home:/home"
      - "/etc/passwd:/etc/passwd"
      - "/etc/shadow:/etc/shadow"
      - "/etc/group:/etc/group"

    links:
      - queue:rabbitmq
      - cache:redis
      - database:postgres
      - email:maildev


  web:
    image: nginx:alpine
    container_name: drydock-web

    volumes:
      - "./laravel/public:/var/www/public"
      - "./resources/nginx.conf:/etc/nginx/nginx.conf"
      - "./resources/nginx.default.conf:/etc/nginx/conf.d/default.conf"

    links:
      - webapp

    ports:
      - "8080:80"

  #  ____________________________________________________________________________________________________________
  # |____________________________________________________________________________________________________________|

  cron:
    image: atrauzzi/laravel-drydock
    # See: https://github.com/docker/compose/issues/1617
    #extends: webapp
    container_name: drydock-cron
    # vixie cron jsut doesn't like running in a container, use devcron instead!
    entrypoint: "devcron.py"
    command: ["/etc/cron.d/laravel"]
    env_file: .development.env
    user: ${UID}

    volumes:
      - "./laravel:/var/www"
      - "./resources/crontab:/etc/cron.d/laravel"

    links:
      - queue:rabbitmq
      - cache:redis
      - database:postgres
      - email:maildev


  worker:
    image: atrauzzi/laravel-drydock
    # See: https://github.com/docker/compose/issues/1617
    #extends: webapp
    container_name: drydock-worker
    entrypoint: "artisan"
    command: "queue:listen --sleep=8"
    env_file: .development.env
    user: ${UID}

    volumes:
      - "./laravel:/var/www"

    links:
      - queue:rabbitmq
      - cache:redis
      - database:postgres
      - email:maildev
